import os

HTTP_NOT_FOUND = 404

JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24時間

COOKIE_NAME = "access_token"
COOKIE_MAX_AGE = 60 * 60 * 24  # 24時間（秒）
SECURE_COOKIES = os.getenv("SECURE_COOKIES", "false").lower() == "true"

ARTICLES_PER_PAGE = 15

ACCESS_LOG_COOKIE_EXPIRE_SECONDS = 60 * 60 * 12  # 12時間
ACCESS_LOG_COOKIE_NAME_PREFIX = "article_visit_"
