"""add published to articles

Revision ID: 577e74b6aad3
Revises: 2a8a3b7e8cd9
Create Date: 2026-03-28 12:34:23.838995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577e74b6aad3'
down_revision: Union[str, Sequence[str], None] = '2a8a3b7e8cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published')
    # ### end Alembic commands ###
