"""add published_at to articles

Revision ID: b25bcd30efcc
Revises: b4c9d2e1f3a0
Create Date: 2026-04-11 14:53:02.049424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25bcd30efcc'
down_revision: Union[str, Sequence[str], None] = 'b4c9d2e1f3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published_at')
    # ### end Alembic commands ###
